---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  tasks:
    - import_tasks: tasks/apt_install.yml
      when: apt_install
      tags: ["apt_install"]
    - import_tasks: tasks/docker.yml
      when: docker
      tags: ["docker"]
    - import_tasks: tasks/zsh.yml
      when: zsh
      tags: ["zsh"]
