---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  tasks:
    - import_tasks: tasks/apt_install.yml
      tags: ["apt_install"]
    - import_tasks: tasks/docker.yml
      tags: ["docker"]
    - import_tasks: tasks/zsh.yml
      tags: ["zsh"]
    - import_tasks: tasks/setup_urecon.yml
      tags: ["setup_urecon"]
    - import_tasks: tasks/start_postgres.yml
      tags: ["start_postgres"]
    - import_tasks: tasks/start_oracle.yml
      tags: ["start_oracle"]
