---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir}}/config.yml"
      tags: ["always"]

  tasks:
    # - import_tasks: tasks/apt-update.yml
    #   when: apt-update
    #   tags: ["apt-update"]
    - import_tasks: tasks/apt-install.yml
      when: apt-install
      tags: ["apt-install"]
