---
- name: Install packages
  become: true
  become_user: root
  apt:
    update_cache: true
    pkg:
      - gawk
      - bat
      - jq
  register: result
# - debug:
#     msg={{ result.stdout.split('\n')[:-1] }}
