---
- name: Install docker
  become: true
  become_user: root
  apt:
    update_cache: true
    name: docker.io
  register: result
# - debug:
#     msg={{ result.stdout.split('\n')[:-1] }}
# Also systemctl enable docker
- name: Docker post-install "usermod -aG docker $USER"
  shell: usermod -aG docker {{ ansible_user }}
  become: true
  become_user: root
