---
- name: Create folder /opt/oracle/data with o+w permissions. Owner and group base on the user running the playbook. '/opt/oracle' might not exist yet.
  file:
    path: /opt/oracle/data
    state: directory
    mode: 0775
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes
  become_user: root
- name: Copy docker-compose.oracle.yml into /opt/oracle
  copy:
    src: "{{ playbook_dir }}/compose/docker-compose.oracle.yml"
    dest: /opt/oracle/docker-compose.oracle.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
  become: yes
  become_user: root
# - name: Docker compose up ORACLE
#   shell: docker compose -f docker-compose.oracle.yml up -d
#   args:
#     chdir: /opt/oracle
#   become: yes
#   become_user: root
