version: '3.8'

services:
  postgres-db:
    image: docker.io/postgres:15.3
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: YourPassword
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data